# Generated by Django 2.1.5 on 2019-03-28 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='Укажите время события', verbose_name='дата')),
                ('is_online', models.BooleanField(default=True, help_text='Есть связь с сервером?', verbose_name='онлайн')),
            ],
            options={
                'verbose_name': 'событие',
                'verbose_name_plural': 'события',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(help_text='Укажите адрес электронной почты', max_length=254, verbose_name='адрес')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='IP')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
            ],
            options={
                'verbose_name': 'сервер',
                'verbose_name_plural': 'серверы',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='server',
            field=models.ForeignKey(help_text='Выберите сервер из списка', on_delete=django.db.models.deletion.CASCADE, to='servermon.Server', verbose_name='сервер'),
        ),
    ]
